name: godzilla-deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build-godzilla
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --project=s2-demo-godzilla
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
